# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7b39765b3d4b2d03a9391e4546db7c3dff70ba32b50a2e87a18e1fc20f2c5bf766fa8a9ca1dbd0567c451d021ba756dc430c077d2b3e21fd7491dbe7a0f81b

test:
  secret_key_base: 725287f3e6036a5ffe0cca9c41482b7ed0b803ad0e84aad5d2306dbd2dcdef4fdd826cb7f1a79463fe6fc6bfcf132f887121c3fea5bb79f23d60bb78a740ceab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
